language: node_js
node_js:
  - 6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
